// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKGLSZS1YowKWbPHkgp_nm6O0NsfdQKHA',
    appId: '1:835240027261:web:94e059fcb557fd861c7d14',
    messagingSenderId: '835240027261',
    projectId: 'moharek-e353b',
    authDomain: 'moharek-e353b.firebaseapp.com',
    storageBucket: 'moharek-e353b.firebasestorage.app',
    measurementId: 'G-NCPDDQ1MXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUIUfeqUDEUhbVKkHTMRrUygK67MdhBTM',
    appId: '1:835240027261:android:e6e316af9f636cfb1c7d14',
    messagingSenderId: '835240027261',
    projectId: 'moharek-e353b',
    storageBucket: 'moharek-e353b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgUxo29OMhklhCAclr-QxcYpn0Vcu9xJ4',
    appId: '1:835240027261:ios:27df40cb95cb59ce1c7d14',
    messagingSenderId: '835240027261',
    projectId: 'moharek-e353b',
    storageBucket: 'moharek-e353b.firebasestorage.app',
    iosBundleId: 'com.example.moharekApp',
  );

}