// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'rabhan_firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrWQ5C6AiYHjXVgPGrcbR3s6xvRuVlMWA',
    appId: '1:524026992362:web:96b45d1a76015575622993',
    messagingSenderId: '524026992362',
    projectId: 'rabhan-1ac1f',
    authDomain: 'rabhan-1ac1f.firebaseapp.com',
    storageBucket: 'rabhan-1ac1f.firebasestorage.app',
    measurementId: 'G-KRL27988QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDquuV0caCOitOeXazpf8Dmfdsnywsed6A',
    appId: '1:524026992362:android:6dabef5fb1972a94622993',
    messagingSenderId: '524026992362',
    projectId: 'rabhan-1ac1f',
    storageBucket: 'rabhan-1ac1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMHZm-JrO2YYyyWKQfLAdI2ZquFTEVLkY',
    appId: '1:524026992362:ios:41e16ea01dbfb6aa622993',
    messagingSenderId: '524026992362',
    projectId: 'rabhan-1ac1f',
    storageBucket: 'rabhan-1ac1f.firebasestorage.app',
    iosBundleId: 'com.zbooma.rabhan',
  );
}
